### ISSUE TITLE
交流

### ISSUE THREAD

**Issue by nekozou** [csfive/docs#75]
你好，我对你们的项目很感兴趣，请问是否可以进一步交流？
我的邮件是：<nekoken2002@hotmail.com>

**Comment by mancuoj** [comment]
加 discord 吧

**Comment by nekozou** [comment]
> 加 discord 吧

wow，回复这么快的吗

**Comment by mancuoj** [comment]
有邮件提醒，可以在网站右上角加 discord 聊天
